version: "3.9"
#name: indepo-site

services:
  db:
    image: postgres:15
    container_name: indepo_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      # Если хотите хранить на хосте:
      # - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: indepo_web
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./vol/static:/static
      - ./vol/media:/media
      # если нужно редактировать код без пересборки:
      # - ./:/app
    # Порт наружу не публикуем — ходим через nginx
    expose:
      - "8000"

  nginx:
    image: nginx:1.25-alpine
    container_name: indepo_nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./vol/static:/static:ro
      - ./vol/media:/media:ro

volumes:
  db_data:
